# Generated by Django 6.0.6 on 2026-06-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "material_id",
                    models.SlugField(max_length=100, primary_key=True, serialize=False),
                ),
                ("material_name", models.CharField(max_length=255)),
                ("leather_type", models.CharField(max_length=80)),
                ("sku", models.CharField(max_length=100)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                (
                    "total_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("batch_count", models.PositiveIntegerField(default=0)),
                ("tag", models.CharField(blank=True, max_length=50)),
                ("tint", models.CharField(blank=True, max_length=20)),
                ("swatches", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("customer", models.CharField(max_length=255)),
                ("fulfillment", models.CharField(max_length=50)),
                ("delivery_address", models.TextField(blank=True)),
                ("order_description", models.TextField(blank=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("payment_method", models.CharField(max_length=50)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "batch_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("size_sqft", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("company", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("dimensions", models.CharField(blank=True, max_length=80)),
                ("quality_grade", models.CharField(blank=True, max_length=80)),
                ("added", models.CharField(blank=True, max_length=80)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="api.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=255)),
                ("batch_code", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("qty", models.PositiveIntegerField()),
                ("size_sqft", models.DecimalField(decimal_places=2, max_digits=12)),
                ("custom_size", models.CharField(blank=True, max_length=80)),
                ("color", models.CharField(blank=True, max_length=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
            ],
        ),
    ]
