# Generated by Django 5.2.15 on 2026-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_orderitem_id_audittrail"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="entity_name",
            field=models.CharField(
                blank=True,
                help_text="Material name, leather type, or identifying info",
                max_length=255,
            ),
        ),
    ]
