# Generated by Django 5.2.15 on 2026-06-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_audittrail_entity_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="dimensions",
        ),
    ]
