# Generated by Django 5.2.15 on 2026-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_batch_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
