# Generated by Django 6.0.6 on 2026-06-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_audittrail_id_alter_batch_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='sku',
        ),
    ]
